---
- hosts: all
  roles:
   - role: 'roles/HSC/monitoring'
     tags:
       - hold_HSC
   - role: 'roles/common/window_hardening'
     tags:
       - window_hardening
   - role: 'roles/common/linux_hardening'
     tags:
       - linux_hardening
   - role: 'roles/common/splunk_win'
     tags:
       - splunk_win
   - role: 'roles/common/splunk_lin'
     tags:
       - splunk_lin
  
