---
- hosts: all
  roles:
   - role: 'roles/HSC/monitoring'
     tags:
       - hold_HSC
   - role: 'roles/common/webtier'
     tags:
       - hold_common
   - role: 'roles/common/hardening_role'
     tags:
       - hold_Hard
  
