---
- name: Prompt User to Change Password
  win_regedit:
    path: "{{ password_expiry_warning.path }}"
    name: "{{ password_expiry_warning.name }}"
    data: "{{ password_expiry_warning.value }}"
