---
- name: Prompt User to Change Password
  win_regedit:
    path: "{{ hardening_requirements.windows_hardening.password_section.password_expiry_warning.path }}"
    name: "{{ hardening_requirements.windows_hardening.password_section.password_expiry_warning.name }}"
    data: "{{ hardening_requirements.windows_hardening.password_section.password_expiry_warning.value }}"
