---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: jyaggarwal/newProject@master
        with:
          command: lint
          version: 2.298.2
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image:
          - ubuntu
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: jyaggarwal/newProject@master
        with:
          version: 2.298.2
          image: "${{ matrix.image }}"
          options: parallel
          scenario: my_specific_scenario
